# Generated by Django 4.2.7 on 2023-12-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechaInscripcion', models.DateField()),
                ('horaInscripcion', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=150)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.instituciones')),
            ],
        ),
    ]
